### ISSUE TITLE
Error while starting the new game

### ISSUE THREAD

**Issue by katerinamerkulova** [AlexeyMalafeev/kfw-the-game#11]
~~~
C:\Users\merku\Desktop\git\kfw-the-game>python NG_default.py
Traceback (most recent call last):
  File "NG_default.py", line 1, in <module>
    from kf_lib import game
  File "C:\Users\merku\Desktop\git\kfw-the-game\kf_lib\game\__init__.py", line 1, in <module>
    from .game import Game
  File "C:\Users\merku\Desktop\git\kfw-the-game\kf_lib\game\game.py", line 12, in <module>
    from .. import testing_tools  # noqa
  File "C:\Users\merku\Desktop\git\kfw-the-game\kf_lib\testing_tools.py", line 1, in <module>
    from tqdm import trange
ModuleNotFoundError: No module named 'tqdm'
~~~

**Comment by AlexeyMalafeev** [comment]
Fixed, pushed to the dev branch
