### ISSUE TITLE
Crashing at the beginning 

### ISSUE THREAD

**Issue by katerinamerkulova** [AlexeyMalafeev/kfw-the-game#9]
Right after generating of characters, styles and etc. 
```Fang Konggao is now number 6 at his school.```
the game fails with an error: 
```
Traceback (most recent call last):
    File "NG_default.py", line 10, in <module>
        g.new_game(forced_aip_class=DefaultAI)
    File "C:\Users\merku\Desktop\git\kfw-the-game\kf_lib\game\game.py", line 473, in new_game
        self.save_game('test save.txt')
    File "C:\Users\merku\Desktop\git\kfw-the-game\kf_lib\game\game.py", line 681, in save_game
        with open(os.path.join(SAVE_FOLDER, file_name), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'save\\test save.txt'
debugging info saved to "debug.txt"
-FAILED TO SAVE GAME-
```

**Comment by AlexeyMalafeev** [comment]
The fix is now in the dev branch, will merge into master and publish in the next release.

**Comment by AlexeyMalafeev** [comment]
Thank you!
